
.PHONY: usage
usage:
	@echo 'Usage:'
	@echo '  make clean'
	@echo '    remove backup files only'
	@echo '  make clean-all'
	@echo '    remove cache files and backup files'

.PHONY: clean
clean:
	@rm -f *~

.PHONY: clean-all
clean-all:
	@rm -f ./*~ ./__pycache__/*
